# Generated by Django 4.1.3 on 2022-12-04 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.IntegerField()),
                ('availability', models.BooleanField(default=True)),
                ('room_type', models.CharField(choices=[('Executive', 'Executive Room'), ('Standard', 'Standard Room'), ('Villa', 'Villa Room'), ('Double', 'Double Room')], max_length=200)),
                ('price', models.IntegerField()),
                ('room_picture', models.ImageField(upload_to='uploads/')),
            ],
        ),
    ]
