# Generated by Django 4.1.3 on 2022-12-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='days',
            field=models.IntegerField(default=1),
        ),
    ]
